version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: awura_shortener
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build: .
    ports:
      - "18080:18080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
volumes:
  db_data:
